# Notebook imports

In [1]:
import pandas as pd
import numpy as np

# Constants

In [17]:
TRAINING_DATA_FILE = 'SpamData/02_Training/train-data.txt'
TEST_DATA_FILE = 'SpamData/02_Training/test-data.txt'
VOCAB_SIZE = 2500

# Read and Load Features from .txt file

In [3]:
sparse_train_data = np.loadtxt(TRAINING_DATA_FILE, delimiter=' ', dtype=int)

In [4]:
sparse_test_data = np.loadtxt(TEST_DATA_FILE, delimiter=' ', dtype=int)

In [9]:
sparse_train_data[:5]

array([[ 0,  2,  1,  1],
       [ 0,  3,  1,  2],
       [ 0,  4,  1,  1],
       [ 0,  7,  1,  3],
       [ 0, 11,  1,  1]])

In [11]:
sparse_train_data[-5:]

array([[5795, 2033,    0,    1],
       [5795, 2036,    0,    2],
       [5795, 2278,    0,    1],
       [5795, 2339,    0,    1],
       [5795, 2357,    0,    1]])

In [13]:
print('Nr of rows in training file: ', sparse_train_data.shape[0])
print('Nr of rows in testing file: ', sparse_test_data.shape[0])

Nr of rows in training file:  258358
Nr of rows in testing file:  117782


In [16]:
print('Nr of emails in training file: ', np.unique(sparse_train_data[:, 0]).size)
print('Nr of emails in testing file: ', np.unique(sparse_test_data[:, 0]).size)

Nr of emails in training file:  4013
Nr of emails in testing file:  1724


## Creating An Empty Dataframe

In [18]:
column_names = ['DOC_ID'] + ['CATEGORY'] + list(range(0, VOCAB_SIZE))
column_names[:5]

['DOC_ID', 'CATEGORY', 0, 1, 2]

In [19]:
index_names = np.unique(sparse_train_data[:, 0])
index_names

array([   0,    1,    2, ..., 5791, 5794, 5795])

In [21]:
full_train_data = pd.DataFrame(index=index_names, columns=column_names)
full_train_data.fillna(value=0, inplace=True)
full_train_data.head()

DOC_ID  CATEGORY  0  1  2  3  4  5  6  7  ...  2490  2491  2492  2493  \
0       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
1       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

   2494  2495  2496  2497  2498  2499  
0     0     0     0     0     0     0  
1     0     0     0     0     0     0  
2     0     0     0     0     0     0  
3     0     0     0     0     0     0  
4     0     0     0     0     0     0  

[5 rows x 2502 columns]